# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = { device = "/dev/disk/by-id/nvme-ZHITAI_TiPlus5000_1TB_ZTA21T0KA222520MB7-part3"; fsType = "ext4"; };
  fileSystems."/boot" = { device = "/dev/disk/by-id/nvme-ZHITAI_TiPlus5000_1TB_ZTA21T0KA222520MB7-part1"; fsType = "vfat"; options = [ "fmask=0022" "dmask=0022" ]; };
  swapDevices = [{ device = "/dev/disk/by-id/nvme-ZHITAI_TiPlus5000_1TB_ZTA21T0KA222520MB7-part2"; }];


# fileSystems."/" = { device = "/dev/disk/by-label/root"; fsType = "ext4"; };
# fileSystems."/boot/efi" = { device = "/dev/disk/by-label/boot"; fsType = "vfat"; options = [ "fmask=0022" "dmask=0022" ]; };
# swapDevices = [ { device = "/dev/disk/by-label/swap"; } ];

  # fileSystems."/" =
  #   { device = "/dev/disk/by-uuid/ee4719bc-1457-4b22-890e-59d595a11721";
  #     fsType = "ext4";
  #   };
  #
  # fileSystems."/boot/efi" =
  #   { device = "/dev/disk/by-uuid/48BA-65BE";
  #     fsType = "vfat";
  #     options = [ "fmask=0022" "dmask=0022" ];
  #   };
  #
  # swapDevices =
  #   [
  #     { device = "/dev/disk/by-uuid/757051e9-379a-4f95-be19-ce203da6df61"; }
    # ];

# sudo fatlabel /dev/nvme0n1p1 boot
# sudo e2label /dev/nvme0n1p3 root

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
