* ZEN
#+begin_Verse
Delete your windows,
Throw away mouse,
Install NixOS for Linux,
Install Emacs with Sway,
Config they until you can flow
in 36 keys split ZMK keyboard
in Colemak-DH layout (and wubi-like chinese-input-method)
with one Eink screen,
no music, no movie, no game, no news, no video, no social-media, no phone, no player, no browser,
It is Thinking Machine, Not Skinner's BOX.
no LLM, no LSP, no syntax highlight, no realtime checker, no network-must, no property-app, no blogging,
Thinking by Writting, Not by Prompting.
Just Emacs and GCC, Simple and Sinister.
You learn C by C-Manual in Info,
You learn elisp by Elisp-Intro in Info,
You learn C std by read though Libc/Posix manuals in Info,
You learn elisp std by read though Elisp/Emacs manuals in Info,
You learn some interesting pkgs in emacs to learn navigate code,
You learn some interesting pkgs in nixos to learn github and wiki.
You learn the project you interesting to have mental model,
You learn the naming and organization of the struct/function of it,
You finally finished hot leetcode tasks and your own projects.
Go for company or do your indie creativity things.
You know "the industira revolution and it's consequence has been a disaster for human race."
You choose linux/emacs, because it's hard way for fun, that's all life about, Pain give us a purpose.
Simple and Sinister. Sleep and Love. Leere and Learn.
#+end_verse


世界嘈杂、瘾品横流、随机与即时构成新的枷锁，而真正的自由来自主动的剥离。当目光离开诱惑、离开广告、离开无意义的瞬息刺激，心才开始变得干净。生活越简，能量越纯；越慢，感受越深；越少，越能看见真正的自己。

身体是意志的第一块土地。空腹的清明、弱光的安静、低温的醒觉、缓慢进食的耐性，都在一点点重塑我们早已被工业习惯磨钝的感官。行走、奔跑、提举、拉起、俯卧撑、壶铃、农夫行走——这些最朴素的动作让人重新理解力量的意义：力量不是爆发，而是日复一日不受伤、不懈怠、让心跳稳、饮食亦是自律的延伸。

避免加工。让精神长的那种沉稳、远离高糖盐油，回到豆果菜、坚果与发酵的本味，让身体习惯真实的能量，而不是被化学甜味与工业脂肪驱使的假饱与假快乐。克制不是苦行，而是温和地恢复本能。

至于技术，真正的价值不在追逐流行，而在深入底层、理解根本。用 Emacs，不是为了高效，而是为了与世界拉开距离，与自己靠得更近；不随机、不即时、无广告、无噪声，是一种长期的心性训练。读 LFS、LKD 与 SOC 文档，写驱动、调性能、跑 QEMU、玩内核、读源码、用\LaTeX{}和Org写书，是为了获得一种“我真的懂了”的安静感。而这种懂，不是为了炫耀，不是为了沉迷，而是为了让工作成为谋生技能，让生活成为真正的生活。

真正的智慧是：学会技术，然后把技术放下；拥有力量，然后让力量变得温柔。生活是吃饭、睡觉、读书、编程、走路、壶铃；生命是健康、乐观、会意、精进、闲适与稳稳的力量。

世界广袤、事物繁多，而心若清澈，幸福忽然变得极小，也极近——不来自外界，只来自自身安静而坚定的内心。

* Leere

#+begin_Verse
居事寂静而世事安宁。

I was what I walk and see,
come out to be.

文灭志，博溺心。

- No Phone, No Internet, No Browser, No IDE, On Plain Text, Consume->Creat.
- Master NixOS/Emacs, For Into Boring Stable and Fluent MindFlow Mode.
- Read HTML Reference, Manual, Info, Help, Compilation, Source Code.
- Master C language and it's Std, and library often used with debug exprience.
- Do Leetcode, Learn Algorithm and Data Structure, Exciting to Solving Tasks.
- Do Flag.h/Paperlike-cli/WM/RTOS, Learn Real programming For Myself.
- Accumulate a codebase, Use Erlang/Zig/Rust to creat project You Like.
#+end_Verse


A 20s Old man yell at Cloud.

---------------------------------------------------------------------------------------


Phone is about 24h slaving human close-source which full of spyware made by Jews/Chinese, they make consumers arguing over and over about brand/chips/products/new fasion/new shitty color.

People consume the phone shit, like it's part of they body, they dress the phone, they customize themes, they delete apps, they seems like owner of the phones. However, Phone Own Their Users.

People use this kind tool mainly just for sex trade, pretend sociable in hundreds of fake relationship groups, and make boss slave empolyee out of their working time, make people distance each other becase "they can social in phones, easily". and due to shitty phone, people no long trust each other,
every message can transmit means it can save, so every chat is like public speaking,
and it's not like public speaking, image you are in a chat group in reality, there will be not everyone will know what you are saying, but int chatting apps, every word is store in database, every thing you do is unforgeable.

so, people less and less social in reality, and more and more addict to phone anoy chatting, is a unhuman way to live in such "modern world".

Smart phone ads tell us that the 5G shits and big camera shit, but in reality, phone more ofthen show you ads, shotting personal porn, sharing mindless videos and misinformation, phone is useless on mindful things, it just popout endless app and shitty small screen artical which full of garbage ads.

Come and consume new phones, we have Back Screen to bring back feeling of 90s which watch porn on tiny screen and "AI Phone" to help you make fancy todo-list, and shopping junk food, the price is only need to cut off you hands and smaller you brain, because you don't need they anymore.

---------------------------------------------------------------------------------------


Actually, No Internet, there will be no Browser/Phone, But Internet is not totally evil, so you can see this blogging. Internet is aboubt blogging garbage, spread fear. All in all, Freedom Cause Compulsive Abuse.



---------------------------------------------------------------------------------------


Browser is gateway of porn and doomscroll, you search, jerk off, comment, browsing, blogging, ship electron app with chromium to everyone's phone and pc to help phone brand sell more new phones.  Just make living for javascript web devs by share your pravicy to shopping tech company.


---------------------------------------------------------------------------------------

IDE give you LSP, LLM to help M$ gain 100 billion$,
LSP Just give you tons of distraction, and fake feelings of understanding a project, it pop out when you learning, typing, the aim is to make people no longer able to write programs that work.

LLM just give you a chatbox to help you modify code you generate from LLM which is already sucks enough, by that way, you lost you own ability to modify text, you just chat and chat, You don't know your code by mental model, you just find bug at compiletime and runtime at launch, you are doomed to really love programming, you just a interface of BOSS to LLM.

LSP and 100 fancy color themes with 1 million panels and Javascript Extensions, will not save you from pain of learning, they excuses for lazy people who can't read code at all. they don't remember what function they want to use, they wait for lsp load codebase and popout endless list of useless functions, and using white on dark with 1000 "true-colors" theme for the "syntax highling" eye candy, They don't READ, They Browsing, They don't remember, They LSP, They don't modifying, They LLM, They don't Read Manual, They Searching.

Busy-minds cause Less Mindful.


#+TITLE: TL;DR
#+OPTIONS: toc:2
#+language: cn
#+LATEX_CLASS: elegantbook
#+LATEX_CLASS_OPTIONS: [color=black, citestyle=gb7714-2015, bibstyle=gb7714-2015,lang=cn,math=cm,10pt, scheme=chinese,toc=twocol,bibend=bibtex]
#+LATEX_HEADER: \subtitle{Simplicity Is The Key}
#+LATEX_HEADER: \title{My TL;DR Notes}
#+LATEX_HEADER: \institute{Free Club}
#+LATEX_HEADER: \bioinfo{邮箱}{llqingsong@qq.com}
#+LATEX_HEADER: \setcounter{tocdepth}{2}
# #+LATEX_HEADER: \logo{.jpg}
#+LATEX_HEADER: \cover{~/.local/share/mysource/meditate.jpg}
#+LATEX_HEADER: \usepackage{array}
#+LATEX_HEADER: \usepackage{cprotect}
#+LATEX_HEADER: \definecolor{customcolor}{RGB}{255,255,255}
#+LATEX_HEADER: \colorlet{coverlinecolor}{customcolor}
# #+LATEX_HEADER: \addbibresource[location=local]{reference.bib}
#+keywords: Tech, NestorLiao, FSF, Emacs, Linux, ZMK, Eink, Rust, Zig, C, C++, OS
#+description: NestorLiao, Emacs, Linux, ZMK, Eink, Rust, Zig, C, C++, OS, embedded, tutoria
# #+bibliography: "./reference.bib"
#+cite_export: bibtex
#+LATEX_HEADER: \mainmatter
