#+AUTHOR: QingSong Liao
#+EMAIL: llqingsong@qq.com
#+HTML_CONTAINER_CLASS: container
#+HTML_DOCTYPE: html5
#+HTML_HEAD: <link rel="stylesheet" href="./mystyle.css">
#+HTML_HEAD: <meta charset="utf-8">
#+HTML_HEAD: <meta name="viewport" content="width=device-width, initial-scale=1">
#+HTML_HEAD: <style> :root{--customcolor: #ffffff} .coverline{color:var(--customcolor);} </style>
#+HTML_HEAD_EXTRA: <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;700&display=swap" rel="stylesheet">
#+HTML_HTML5_FANCY: t
#+LATEX_CLASS: elegantbook
#+LATEX_CLASS_OPTIONS: [color=black, citestyle=gb7714-2015, bibstyle=gb7714-2015,lang=cn,math=cm,10pt, scheme=chinese,toc=twocol,bibend=bibtex]
#+LATEX_HEADER: \addbibresource[location=local]{reference.bib}
#+LATEX_HEADER: \bioinfo{邮箱}{llqingsong@qq.com}
#+LATEX_HEADER: \cover{~/.local/share/mysource/fly.jpg} \logo{~/.local/share/mysource/meditate.jpg}
#+LATEX_HEADER: \definecolor{customcolor}{RGB}{255,255,255} \colorlet{coverlinecolor}{customcolor}
#+LATEX_HEADER: \institute{Free Club}
#+OPTIONS: toc:2
#+SUBTITLE: Tech among Life and Work
#+TITLE: 技术时代的生活与工作
#+bibliography: "./reference.bib"
#+cite_export: bibtex
#+description: NestorLiao, Emacs, Linux, ZMK, Eink, Rust, Zig, C, C++, OS, embedded, tutoria
#+keywords: Tech, NestorLiao, FSF, Emacs, Linux, ZMK, Eink, Rust, Zig, C, C++, OS
#+language: cn

\chapter*{序章\  技术何为?}
\markboth{Introduction}{序章\  技术何为?}

#+begin_verse
- 眼不见生物本能与工业革命驱动的越发泛滥的信息瘾品世界，心为净极简自然身心黑白断网编程
    远离这几点：随机、即时、不必、匿名、免费、易得、广告、失范
    做到这几点：多做事、乐观心、吃饭慢、心跳缓、有手劲、走路快、体重适、无三高、
    衣着素、清淡食、租房住、乡间息、温度低、睡眠香、独处思、归自然、无名言、无社媒
- 空腹放松|整理计划|静暗凉累|精力充沛|恢复身体|提升大脑|增强免疫|调节激素|健康长寿
- 避免受伤|养成运动习惯|兼顾力量有氧平衡柔韧|全天保持活动
   走路|跑步|抡锤|羽毛球|俯卧撑|引体向上
   摇摆|高拉|相扑|深蹲|拉起|侧拉|划船|起立|绕头|绕身|绕腿|风车
   拉举|抓举|挺举|弯举|军推|实心推|借力推|单双手|单流水|双抓举|农夫行走
- 少糖盐油脂加工食品，多绿豆果菜自然有机
   [大豆|氢化|玉米|芥花]油|反式脂肪
   [口香糖|高果糖|苏氯胺|阿斯巴甜]糖
   [油炸|垃圾|高度加工]食品|面[包|条|饼]|奶酒咖
   番茄|红薯|菜花|香菇|小萝卜|鹰嘴豆|牛油果|夏威夷果
   肌酸|苹果醋|坚果奶|红曲米|发酵食品|胶原蛋白粉|墨西哥辣椒粉
   蓝莓|葡萄|柠檬|香菜|大蒜|孜然|菊粉|可可粉|鱼油|特级初榨橄榄油
- emacs = Evenings, Mornings, And a Couple of Saturdays
   不随机(c-h/info，全部文档代码给你，你不服就改)
   不即时(忍住上古体验需是延迟满足高手，编辑器挑人)
   生存感(人生不过吃睡动和一颗极简又折腾的emacs心)
   不匿名(写包/做实名贡献，代码为万人所用，成就感拉满)
   不免费(自由不是免费，自由无私人文精神残存无限计算世界)
   不易得(当今难得的有难度还有生活具体用处的编程素养积累感)
   无广告(完全可控纯文本，空无至虚感宇宙计算禅意与人类崇高理想)
   不失范(极具宗教感，去传教需冥想自省、禁欲克己来数十年如一日修道)
- 刷leetgo|写project，无色无味不闻不问无欲无求禁游戏戒手机卸浏览器罢搜索恨视频
   通过阅读lfs/lkd等相关英文文档和kernel最佳编程实践
   在emacs中使用[c++|c|zig|rust|makefile|bash]-mode和compilation|magit开发:
   基于多种SOC的linux|rtos的spi、can、wifi、audio、video相关驱动程序和
   有良好的低功耗设计和稳定性优化的高性能|高并发|多线程|多进程|socket网络程序
   然后在qemu|docker|k8s|nix环境中使用perf|ftrace|gprof|gdb工具调试程序
   真实的技术哲学是亲身学会技术底层、真正的人生智慧是用技术找工作然后回到生活远离技术
   生活是吃饭、睡觉、读书、编程、走路、壶铃，生命是健康、乐观、会意、精进、闲适、力量
- While the world is tremendously large, the items are anomalously rich,
   only me writting with leere feeling, ture happiness come from nothing but
   within.
#+end_verse

* Old man yell at Cloud(Network service)
#+ATTR_LATEX: :environment quotation
#+BEGIN_QUOTE
       Most of these tools are distractions. I don't want suggestions
       or needling warnings sliding around on my screen while I
       compose and examine programs; I want a quiet space to
       write and think. Focus is essential.
#+END_QUOTE

---------------------------------------------------------------------------------------

Phone is about 24h slaving human close-source which full of spyware made by Jews/Chinese, they make consumers arguing over and over about brand/chips/products/new fasion/new shitty color.

People consume the phone shit, like it's part of they body, they dress the phone, they customize themes, they delete apps, they seems like owner of the phones. However, Phone Own Their Users.

People use this kind tool mainly just for sex trade, pretend sociable in hundreds of fake relationship groups, and make boss slave empolyee out of their working time, make people distance each other becase "they can social in phones, easily". and due to shitty phone, people no long trust each other,
every message can transmit means it can save, so every chat is like public speaking,
and it's not like public speaking, image you are in a chat group in reality, there will be not everyone will know what you are saying, but int chatting apps, every word is store in database, every thing you do is unforgeable.

so, people less and less social in reality, and more and more addict to phone anomy chatting, is a unhuman way to live in such "modern world".

Smart phone ads tell us that the 5G shits and big camera shit, but in reality, phone more ofthen show you ads, shotting personal porn, sharing mindless videos and misinformation, phone is useless on mindful things, it just popout endless app and shitty small screen artical which full of garbage ads.

Come and consume new phones, we have Back Screen to bring back feeling of 90s which watch porn on tiny screen and "AI Phone" to help you make fancy todo-list, and shopping junk food, the price is only need to cut off you hands and smaller you brain, because you don't need they anymore.

---------------------------------------------------------------------------------------

Actually, No Internet, there will be no Browser/Phone, But Internet is not totally evil, so you can see this blogging. Internet is aboubt blogging garbage, spread fear. All in all, Freedom Cause Compulsive Abuse.

---------------------------------------------------------------------------------------

Browser is gateway of porn and doomscroll, you search, jerk off, comment, browsing, blogging, ship electron app with chromium to everyone's phone and pc to help phone brand sell more new phones.  Just make living for javascript web devs by share your pravicy to shopping tech company.

---------------------------------------------------------------------------------------

IDE give you LSP, LLM to help M$ gain 100 billion$,
LSP Just give you tons of distraction, and fake feelings of understanding a project, it pop out when you learning, typing, the aim is to make people no longer able to write programs that work.

LLM just give you a chatbox to help you modify code you generate from LLM which is already sucks enough, by that way, you lost you own ability to modify text, you just chat and chat, You don't know your code by mental model, you just find bug at compiletime and runtime at launch, you are doomed to really love programming, you just a interface of BOSS to LLM.

LSP and 100 fancy color themes with 1 million panels and Javascript Extensions, will not save you from pain of learning, they excuses for lazy people who can't read code at all. they don't remember what function they want to use, they wait for lsp load codebase and popout endless list of useless functions, and using white on dark with 1000 "true-colors" theme for the "syntax highling" eye candy, They don't READ, They Browsing, They don't remember, They LSP, They don't modifying, They LLM, They don't Read Manual, They Searching.

Busy-minds cause Less Mindful, why not do just below things:
Delete your windows,
Throw away mouse,
Install NixOS for Linux,
Install Emacs with Sway,
Config they until you can flow
in 36 keys split ZMK keyboard
in Colemak-DH layout (and wubi chinese-input-method)
with one Eink screen,
No music, No movie, No game, No news, No video, No social-media, No phone, No player, No browser,
It's Thinking Machine, Not Skinner's BOX.
No LLM, No LSP, No syntax highlight, No realtime checker, No network-must, No property-app, No blogging,
Thinking by Writting, Not by Prompting.
See With Your Mind, Not Your Eye.
Just Emacs and GCC, Simple and Sinister.
You learn C by C-Manual in Info,
You learn elisp by Elisp-Intro in Info,
You learn C std by read though Libc/Posix manuals in Info,
You learn elisp std by read though Elisp/Emacs manuals in Info,
You learn some interesting pkgs in emacs to learn navigate code,
You learn some interesting pkgs in nixos to learn github and wiki.
You learn the project you interesting to have mental model,
You learn the naming and organization of the struct/function of it,
You finally finished hot leetcode tasks and your own projects.
Go for company or do your indie creativity things.
You know "the industira revolution and it's consequence has been a disaster for human race."
You choose linux/emacs, because it's hard way for fun, that's all life about, Pain give us a purpose.
Simple and Sinister. Sleep and Love. Leere and Learn.


---------------------------------------------------------------------------------------
